version: '3.8'

services:
  detec-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: detec-backend
    ports:
      - "8000:7860"
    restart: always
    volumes:
      - detec-data:/home/user/app/uploads
      - detec-db:/home/user/app/detec.db

volumes:
  detec-data:
  detec-db:
